[package]
name = "real-time-terminal"
version = "0.1.0"
edition = "2021"

[dependencies]
env_logger = "0.11.3"
futures-util = "0.3.30"
log = "0.4.21"
tokio = { version = "1.38.0", features = ["full"] }
tokio-tungstenite = { version = "0.23.1", features = ["native-tls"] }
futures-channel = "0.3.28"
